<?php
/**
 * @file
 * Primary hook implementations for Metatag: GSB Public.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function gsb_public_custom_metatags_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_metatag_info().
 */
function gsb_public_custom_metatags_metatag_info()
{
  $info['groups']['gsb-metatags'] = array(
    'label' => t('GSB Metatags'),
    'description' => t('A set of meta tags specifically for the GSB Public Site</a>.', array('!url' => 'http://gsb.stanford.edu/')),
    'form' => array(
      '#weight' => 70,
    ),
  );

  // GSB meta tags stack after the Twitter tags.
  $weight = 70;

  // Defaults used for all cards.
  $defaults = array(
    'class' => 'DrupalTextMetaTag',
    'group' => 'gsb-metatags',
    //'element' => array(
    //'#theme' => 'metatag_gsb_metatags',
    //),
  );

  $info['tags']['gsb-metatags:dimension1'] = array(
    'label' => t('GTM Dimension 1'),
    'description' => t('Notes: Dimension 1 is used by Google Tag Manager'),
    'weight' => ++$weight,
  ) + $defaults;

  $info['tags']['gsb-metatags:dimension2'] = array(
    'label' => t('GTM Dimension 2'),
    'description' => t('Notes: Dimension 2 is used by Google Tag Manager'),
    'weight' => ++$weight,
  ) + $defaults;

  $info['tags']['gsb-metatags:dimension3'] = array(
    'label' => t('GTM Dimension 3'),
    'description' => t('Notes: Dimension 3 is used by Google Tag Manager'),
    'weight' => ++$weight,
  ) + $defaults;

  $info['tags']['gsb-metatags:dimension4'] = array(
    'label' => t('GTM Dimension 4'),
    'description' => t('Notes: Dimension 4 is used by Google Tag Manager'),
    'weight' => ++$weight,
  ) + $defaults;

  return $info;
}
